### ISSUE TITLE
read only protocol definitions

### ISSUE THREAD

**Issue by MarcusWolschon** [MasterTailer/CRUMPET#117]
Please check in an editable version of "DIGITAiL PROTOCOL v1.3.pdf", so we can add missing data.
Using a markdown file instead of pdf and Microsoft Word would have been better for editing and version control.

**Comment by darkgrue** [comment]
[Tail Command Protocol](https://github.com/MasterTailer/CRUMPET/wiki/Tail-Command-Protocol) added to wiki as editable document (one image pending add to repo). Ear Gear document will get similar treatment shortly.

**Comment by darkgrue** [comment]
[Wiki](https://github.com/MasterTailer/CRUMPET/wiki) updated and Pull Request https://github.com/MasterTailer/CRUMPET/pull/129 created for Wiki images.
