### ISSUE TITLE
Enhancement: Rescan for Devices

### ISSUE THREAD

**Issue by darkgrue** [MasterTailer/CRUMPET#123]
Feature request: there should be a way to rescan for devices any time before "connect" is pressed.

**Comment by darkgrue** [comment]
I also just noted that there's no way to _stop_ scanning, other than closing the app. Which might have a significant impact on phone life if the app continues to scan in the background (not sure if that actually happens or not, with the way apps background and how the BTLE stack works?).

**Comment by leinir** [comment]
It stops scanning after a little while (as in, it's only scanning when that little rotating thing is going), so that's nothing much to worry about. The other part though, rescanning should be a thing, and it's in f7c1cd962e815928498ddcb0a02f4a47c248ebb4
