### ISSUE TITLE
Enhancement: Add Support for Glow Tip Detection

### ISSUE THREAD

**Issue by darkgrue** [MasterTailer/CRUMPET#133]
Add support for Glow Tip detection as implemented in MiTail Firmware v4.0.0.

Notional tasks:
Hide and show Glow Tip moves based on whether a Glow Tip MiTail is connected
Correctly handle DIGITAiLs
Correctly handle a mix of Glow Tip and non-Glow Tip tails

**Comment by leinir** [comment]
Done in 024c94b11aeccde4cb3746398e3ccc46604cb443
