### ISSUE TITLE
Move naming dialogues so they are in the middle of the screen

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/CRUMPET#82]

**Comment by gilmanov-ildar** [comment]
@MasterTailer, we can not do that while we use not patched `Kirigami.OverlaySheet` for it. We should change the property `topOpenPosition` of the internal object `openAnimation`.

By the way, Kirigami code is not good, and moreover it makes some simple things too complicated for realization. It would be better to use vanilla `QtQuick.Controls2` for the whole project, IMHO.
