### ISSUE TITLE
Centre the "Searching - nothing found" dialogue like the buttons

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/CRUMPET#93]

**Comment by gilmanov-ildar** [comment]
@MasterTailer, please add some screenshots

**Comment by gilmanov-ildar** [comment]
@MasterTailer, it would be wrong decision in my opinion, because all other dialogs have the header texts at the left side, not centered.

**Comment by gilmanov-ildar** [comment]
![centered-text](https://user-images.githubusercontent.com/15459404/58370053-25bde000-7f2c-11e9-9858-3dac4c63caf5.png)

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/104

**Comment by MasterTailer** [comment]
I'm confused. They are all centred here and I think it looks better ...

⁣Master Tailer
http://thetailcompany.com​

**Comment by MasterTailer** [comment]
Be nice if it was centred vertically as well as horizontal
