### ISSUE TITLE
Must have max time on Casual mode!

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/CRUMPET#96]

**Comment by MasterTailer** [comment]
Maybe a warning about extended times being bad?>

**Comment by MasterTailer** [comment]
Shall we say 4 hours?

**Comment by MasterTailer** [comment]
"Maybe its time for Tail rest... Let your tail have a power-nap."

**Comment by gilmanov-ildar** [comment]
@MasterTailer, please could you describe it in more details?

**Comment by MasterTailer** [comment]
When casual mode is switched on in the app, a timer starts independent of anything else. After 4 hours, casual mode is switched off. And a message is shown.

**Comment by gilmanov-ildar** [comment]
![timeout](https://user-images.githubusercontent.com/15459404/58369832-500e9e00-7f2a-11e9-87d8-6d9cf798e5e0.png)

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/103
