### ISSUE TITLE
Make zero battery more obvious 

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/CRUMPET#97]

**Comment by MasterTailer** [comment]
After being at 1 circle for a while, say 2 minutes, lets make it flash? Or do it in red?

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/100

**Comment by gilmanov-ildar** [comment]
We made the batterry level red when `batteryLevel` is less or equal to 1
